### PR TITLE
Github Actions Bot to generate a markdown file of all the albums added in the MDRP Library (finally 🥳 )

### LINKED ISSUE #7: Suggestions with github actions bot
I had these ideas come up as _"ShowerThoughts"_:

3 things 3 bots can do:
1) Generate a markdown file containing the names of albums (sorted alphabetically) added in the Discord application by going through all the dat files in [`User_Generated_Files/`](User_Generated_Files)
2) Another bot to add newly added dat files in [`User_Generated_Files`](User_Generated_Files) into the [`clientdata/`](https://github.com/jojo2357/Music-Discord-Rich-Presence/tree/master/clientdata) folder in [Music-Discord-Rich-Presence](https://github.com/jojo2357/Music-Discord-Rich-Presence), so people can have up-to-date album keys
3) This bot could detect duplicate albums that already exist in the main library in new pull requests

### PR DESCRIPTION
**Pull request by RoguedBear**
I've made the action which will generate a markdown file of all the albums added in the MDRP by going through the `dat` files in `User_Generated_Folder/`
The python script doing that part is: `generate_artists.py` and the output file is `Albums_in_MDRP.md`

- Entries in `dat` files without artist key will be under `Unknown Artist` 
- **all** special characters will be escaped

in the python script i've left the logging in debug mode in case some bugs comes out then there will be logs at hand

I also wanted to mention a few important things that were in my mind the night before, and now I've forgotten it and dont remember it 😓 
(closes #7 )

### CODE REVIEW

**Comment by RoguedBear** [comment]
Remembering 1: 
One issue i remembered is that when an album will have multiple artists (separated with a forward-slash) in the dat file, then artist name will be the combined one with the forwardslashes and not duplicated like the same album name under different artists' headings (like the screenshot I posted in #10)

I could implement a check in a future commit to see whether an album has multiple artists (differentiated by the conventional forward-slash) and then add those albums under those individual artists' headings

let me know what do you think.

**Comment by jojo2357** [comment]
I will do a more thorough review when i get the chance 👍

**Review by jojo2357 — COMMENTED** [review]
This is really minor, but could there also be a plaintext (no escaped chars) version as well? I see why you have to escapes the `md` version just it looks kinda ugly in diff view xD.

**Comment by RoguedBear** [comment]
Okay, i can also create a plaintext file. Though I will admit i went a little overboard with the escaping thing. I could've just escaped `~, _, -, *, >` and the brackets

**Comment by RoguedBear** [comment]
done!
(with the plaintext file, not the escaping thing)

**Comment by jojo2357** [comment]
Is the escaping needed? If so lmk when you complete that and ill merge. If not lmk and ill merge

**Comment by RoguedBear** [comment]
I guess it's fine escaping all the special characters in the `md` file, I won't change that. for the plaintext file nothing is escaped.

**Review by jojo2357 — APPROVED** [review]
Looks good :)

**Comment by jojo2357** [comment]
Tysm!

**Pull request merged**
