### PR TITLE
Actions bot now adds music entries for multiple artists in their own headings, AKA clean markdown files 🍻

### LINKED ISSUE #16: actions bot needs to be updated to properly mention album name with multiple contributing artists under their respective headings
Since multiple artists are now officially added in the Library folder, I've noticed that when multiple artist names are present in the song's metadata and extracted they're separated by forward slash. This is also visible in some parts of the file [Albums_in_MDRP](Albums_in_MDRP.md) such as:
https://github.com/jojo2357/Music-Discord-Rich-Presence-Library/blob/3a4cd04666da76cfe17a1c0fe7975190aab433c2/Albums_in_MDRP.txt#L910

And since the forward slash appears to be the delimiter for multiple artists in a mp3 tag, so what i'm suggesting is that I take this album name and mention it under all the artists' heading in this file whose names are joined together with a forward slash. 
Example referring this line, I'd put `Play` under their (`Alan Walker`, `K-391`, `Tungevaag`, `Mangoo`) headings

But there also also exceptions in this 'forward-slash-delimiter' rule where artists who have a forward slash in their name as on this line with the band `AC/DC` could be separated into `AC` & `DC` which I'm sure no one would like 😄 

https://github.com/jojo2357/Music-Discord-Rich-Presence-Library/blob/3a4cd04666da76cfe17a1c0fe7975190aab433c2/Albums_in_MDRP.txt#L23

So, I would either have to add and maintain a whitelist or use an API to check whether "the artist with forward slashes in the name" exists or not (for this I would have to search for an API, or find a way to get that information)

If this plan is approved, I will work on this when I get time during the weekends.
If you have some suggestions to deal with this issue, then do let me know and I would be happy to consider them.

### PR DESCRIPTION
**Pull request by RoguedBear**
It's been quite a while since these changes were proposed hehe.

Anyways, here's summary of what other changes are also added:

-   [x] Don't write `Unknown Artist`, if its empty
-   [x] when comparing artists, make it case insensitive
-   [x] write the code for the big merge (the title of this PR)
-   [x] escape only `*_~\` and brackets and back-tick. (only those characters, which affect markdown formatting)
         Default setting but can be overridden to escape all characters by setting the environment variable `ESCAPE_ALL` to `1`

---
For the multiple artist thing, I'm maintaining a gist [here](https://gist.github.com/RoguedBear/b0c7028c6ca194f01218d3281644bbc0) which the python script uses to search whether these artists exist in the multiple artist string part.

Then, the album name is added under all the artists' headings. You can have a look at the diff view to see the final result.
<br>
As and when new music files are added, i'll give a look to the logs to see whether any real artist with slashes in their name have been split. (the starting part of the logs will contain this. The logs the script generates floods with a mess of data hehe..)

If any artist is split by mistake and their name is not on the gist, they can either create an issue here, or drop a comment on the gist.
<br><br>
[PS: there's an option to set the trigger of this action only when files under `User_Generated_Folder/**` are changed. I haven't commited that part, cuz it was not easy to test that. It can be still added tho if you don't want the bot running on every single push event]

---
closes #16

### CODE REVIEW

**Comment by jojo2357** [comment]
:o how u do the todo list? Also the commit only on files changed would be redundant?? because otherwise there would be no changes for the bot to commit so it wouldnt commit, right?

**Comment by RoguedBear** [comment]
the checkboxes can be implemented like that:
```markdown
- [ ] empty checkbox
- [x] checked checkbox
```
---
The bot will only commit (or git will let the bot commit) if the generated files were changed, which will only happen when stuff is added in the `User_Generated_Files` folder.

It's just that the action would run on all commits/pushes regardless if the commit was in the `User_Generated_Folder` or from some library code changes.

to change the behavior you would have to change this line 
https://github.com/jojo2357/Music-Discord-Rich-Presence-Library/blob/ee2214503f9b344603870ddae1951e211af89dbb/.github/workflows/generateMDRPLibraryList.yml#L3
to: 
```yaml
on:
  push:
    paths:
      - "User_Generated_Files/**"
```
I haven't tested this but [it should work](https://stackoverflow.com/a/63461325).

**Comment by Smaltin** [comment]
Currently the gist linked is a specific version (the first version in this case.) If you omit everything after `/raw/` then it'll always use the latest.

**Comment by RoguedBear** [comment]
> 
> @Smaltin 
> Currently the gist linked is a specific version (the first version in this case.) If you omit everything after `/raw/` then it'll always use the latest.

Oh shoot! good catch. 
So all this time I've been using gists wrong the entire time 🤦‍♂️ 

I'll fix this right now

**Comment by RoguedBear** [comment]
Converting PR to draft.

I just found out there's more than one way of specifying multiple artists.
1) is what the script generates with multiple artists separated by a forward slash
2) manually by putting `=` as the separator for multiple artists

the code works for 1st condition, but the 2nd one is unaccounted for.
I'll work on the 2nd condition when I get time

**Comment by RoguedBear** [comment]
I have made the commit which accounts for multiple `==` separation.

Turns out due to this filter not being present in earlier version of the script, a lot of artists were missed from the existing files as well.
Whoops..

**Review by jojo2357 — APPROVED** [review]
Looks good to me :)

**Comment by jojo2357** [comment]
@Smaltin just ok it and I'll merge. Sorry I havent been on top of MDRPL recently xD

**Comment by Smaltin** [comment]
Yeah it looks good to me, you're good to go @jojo2357

**Pull request merged**
