### PR TITLE
Smaltin's Big Kahuna (pt. 2)

### PR DESCRIPTION
**Pull request by Smaltin**
Ohhhh yeaaaahhhhh!!!

### CODE REVIEW

**Comment by Smaltin** [comment]
idk why it didn't like the PR earlier but whatever, it works ig

**Comment by jojo2357** [comment]
😑

**Comment by jojo2357** [comment]
More stale than kale

**Comment by jojo2357** [comment]
haha lol totally forgot about this and now it is deprecated

**Pull request closed without merging**
