### PR TITLE
Addition Of Songs

### PR DESCRIPTION
**Pull request by BearTS**
These Includs some of the albums that i bought

### CODE REVIEW

**Comment by jojo2357** [comment]
I will upload these and return an id and merge when i get the chance.

**Comment by BearTS** [comment]
Alright 👍

**Comment by jojo2357** [comment]
Haha I ran out of applications I can make so I will have to just use your apps then... @RoguedBear can you do me a solid and upload your stuff to your own account and pr that? Turns out I unfortunately can't hold onto all of the applications 😩

**Review by BearTS — COMMENTED** [review]
Noice

**Pull request merged**
