### PR TITLE
Adding album arts generated from my music collection.

### LINKED ISSUE #3: Unable to create a PR because groove0, spotify0, musicbee0 are in gitignore
As `groove0`, `musicbee0`, `spotify0` are in `.gitignore`, comparing pull request across forks does not detect the commit with these folders added.

### PR DESCRIPTION
**Pull request by RoguedBear**
closes #3

### CODE REVIEW

**Review by jojo2357 — APPROVED** [review]
I suppose since this is the first one ill merge then immediately create the apps but most times ill be able to let them collect and do em in one sitting ;)

**Comment by jojo2357** [comment]
Oh no! ur arts are teensy for some reason i should probably look into this
image

**Comment by RoguedBear** [comment]
Ah yes, in my own application i had to resize them too. I can batch resize all the images using ImageResizer in powertoys.

Maybe the script can check and print out warnings for the user to resize them to atleast 512x512

**Comment by jojo2357** [comment]
or the script can do it itself ;)

**Comment by RoguedBear** [comment]
Looks like like you have a lot of sample images to test your script out with 😆

**Comment by jojo2357** [comment]
see most recent commit :)

**Comment by jojo2357** [comment]
@RoguedBear please see the even newer commit and lmk that all the files r the right size

**Comment by RoguedBear** [comment]
@jojo2357 I tested the commit 771b3099bc21b0b146c6585f31f7fdbfd6850566, and yes the all the files were generated at 512x512px!!

**Comment by jojo2357** [comment]
@RoguedBear see most recent commit I am changing the way MDRP identifies albums and it will now require an artist field. Please PR the output of the new exe since your current stuff is deprecated

**Comment by RoguedBear** [comment]
@jojo2357 As I was about to commit the new files, I saw that `all.dat` was filled unlike previous times where it was empty.
This time it had all my album names in `<album name>==<artist>>`  format
Is that expected?

**Comment by jojo2357** [comment]
All.dat should have that format. 
The groove dat files should be album==number==artist

**Pull request merged**
